//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductIntakeProduct
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int ProductIntakeId { get; set; }
        public int Count { get; set; }
        public decimal PriceUnit { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductIntake ProductIntake { get; set; }
    }
}
