//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BigShopBase_01Entities : DbContext
    {
        private static BigShopBase_01Entities _context;
        public BigShopBase_01Entities()
            : base("name=BigShopBase_01Entities")
        {
        }

        public static BigShopBase_01Entities GetContext()
        {
            if (_context == null)
                _context = new BigShopBase_01Entities();

            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductCountry> ProductCountry { get; set; }
        public virtual DbSet<ProductIntake> ProductIntake { get; set; }
        public virtual DbSet<ProductIntakeProduct> ProductIntakeProduct { get; set; }
        public virtual DbSet<ProductOrder> ProductOrder { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<StatusIntake> StatusIntake { get; set; }
        public virtual DbSet<StatusOrder> StatusOrder { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
